### PR TITLE
External Service Button

### LINKED ISSUE #1155: Go To HTTPS Button
Feature enhancement request:

I have a use case where I would like for administrators to make virtual machine resources available to internal customers on-demand. RHV Virtual Machine pools are perfect for that. The only catch is that the hosted VMs provide an HTTPS service on port 443. Currently, the user would have to expand their browser to the correct size so that the FQDN is not ellipsized and copy/paste that into another browser window. It would be great if an HTTPS button was in the toolbar that would generically route to whatever HTTPS/443 service the VM is hosting. That would make for a much more cloud like experience for most use cases.

Essentially change this:

Screenshot from 2020-01-21 14-06-39

To look like this:

after

I'm pretty open on this idea, but I think adding this capability to oVirt would open it up to a lot more use cases by allowing administrators to make a cloud-lite self-service experience without provisioning OpenStack.

### LINKED ISSUE #1163: RDP console connect button on Windows VMs does not work
From the VM card list or from the VM details, selecting the "RDP Console" button has no effect.

VM Portal version number: master (1.6.x)

oVirt version number: 4.3

Browser and version: Chrome / FF

Steps to Reproduce:
1. Login and see a Windows VM
2. on the VM Cards list page, click the split button and click "RDP Console"
3. navigate to the Windows VM's details page
4. click the "Console" split button and click "RDP Console"

Actual results: Nothing happens when "RDP Console" is clicked.

Expected results: A `console.rdp` file should be downloaded by the browser with proper definitions for an RDP client to connect to the VM.

Note: All of the other console buttons function as expected.

Example:
ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by rmkraus**
Added an HTTPS button to the VM's action panel. Clicking this
button will open a broser tab on port 443 of the VM. Currently, the
button will be shown as long as the VM is running.

~~This PR is to address #1155 and is currently a work in progress. I am looking for feedback on how to make this code acceptable for merging.~~

Fixes #1155 
Fixes #1163

Thanks!

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rmkraus** [comment]
This is a screenshot of the UI change. 

Screen Shot 2020-01-22 at 3 29 19 AM

File: src/ovirtapi/transform.js [hunk 1]
```diff
@@ -117,6 +118,12 @@ const VM = {
 
       fqdn: vm['fqdn'],
 
+      service: {
```
Comment (michalskrivanek) [inline src/ovirtapi/transform.js]: it would be better to encapsulate that in a single property, like external_service "name/proto/port" and trivially parse it here into those three components

File: src/components/VmActions/index.js [hunk 2]
```diff
@@ -249,16 +250,22 @@ class VmActions extends React.Component {
         id: `${idPrefix}-button-console`,
         items: consoles,
       },
-      {
+    ]
+
+    if (canService(vm.get('service'))) {
```
Comment (michalskrivanek) [inline src/components/VmActions/index.js]: would probably be better to keep the transform.js generic and only expose custom properties, and this canService(or canExternalService) would look up the correct property and parse that x/y/z value

File: src/components/VmActions/index.js [hunk 3]
```diff
@@ -249,16 +250,22 @@ class VmActions extends React.Component {
...
+      const service = vm.get('service').get('proto') + '://' +
+        vm.get('fqdn') + ':' + vm.get('service').get('port')
+      actions.push({
         priority: 0,
         actionDisabled: isPool || !canConsole(status),
-        shortTitle: msg.https(),
+        shortTitle: vm.get('service').get('name'),
         tooltip: msg.httpsService(),
```
Comment (michalskrivanek) [inline src/components/VmActions/index.js]: maybe add the name to the tooltip too?

File: src/ovirtapi/transform.js (hunk 1 above)
Comment (rmkraus) [reply src/ovirtapi/transform.js]: :+1: 
I have made this change.

File: src/components/VmActions/index.js (hunk 2 above)
Comment (rmkraus) [reply src/components/VmActions/index.js]: :+1:

This has been done in the newest commit.

File: src/components/VmActions/index.js (hunk 3 above)
Comment (rmkraus) [reply src/components/VmActions/index.js]: I'm not sure. I'm happy to do it, but it feels a bit like using the word you're defining in the definition. What do you think?

**Comment by rmkraus** [comment]
I've made most of the requested changes. I'm open to conversation on the Tooltip, I don't have any strong feelings on it. We can squash when merging. I think that would be safer than trusting my git-fu! ;-)

This newest version uses a single custom property called `external_service`. The value of this property is a bar delineated list of NAME|PROTOCOL|PORT. Additional services can be defined by separating them with a comma. So:
Service 1|HTTPS|443,Service 2|HTTPS|8080,Service 3|HTTP|80

For every properly formatted service record in the string, a button will be created on the frontend. The button will only be usable if a FQDN is available, the VM canConsole, and it is not a Pool card.

I thought briefly about having all the service buttons in a drop down. However, these services will likely be unrelated things (Ex Cockpit, Jupyter Lab, and PhpMyAdmin) and putting them in one drop down may not be the best UX.

File: src/components/VmActions/index.js [hunk 4]
```diff
@@ -80,6 +81,7 @@ const VmDropdownActions = ({ actions, id }) => {
             confirmation={action.confirmation}
             shortTitle={action.shortTitle}
             icon={action.icon}
+            onClick={action.onClick}
```
Comment (rmkraus) [inline src/components/VmActions/index.js]: I want to draw attention to this change. I think this was a bug, but I could also be missing something.

The onClick action wasn't being passed to the VM Drop Down Action buttons on the VM card view. Only the primary action kept its onClick property. This never caused an issue because all the other actions use a confirmation dialog which was being passed.

Comment (michalskrivanek) [reply src/components/VmActions/index.js]: no idea. possibly a bug indeed. @sjd78 ?

**Comment by michalskrivanek** [comment]
> I've made most of the requested changes. I'm open to conversation on the Tooltip, I don't have any strong feelings on it. We can squash when merging. I think that would be safer than trusting my git-fu! ;-)

ok,np

> This newest version uses a single custom property called `external_service`. The value of this property is a bar delineated list of NAME|PROTOCOL|PORT. Additional services can be defined by separating them with a comma. So:
> Service 1|HTTPS|443,Service 2|HTTPS|8080,Service 3|HTTP|80

thanks, that looks good. I think it would be nicer with "/" (we use that syntax in osinfo) but it's fine as is:) 
 
> For every properly formatted service record in the string, a button will be created on the frontend. The button will only be usable if a FQDN is available, the VM canConsole, and it is not a Pool card.

does it have to be connected to canConsole? it may have a bit too many states...
export function canConsole (state) {
  return ['up', 'powering_up', 'powering_down', 'paused', 'migrating', 'reboot_in_progress', 'saving_state'].includes(state)
}

it may make sense to introduce a new one or use e.g. canSuspend(yeah, the name is inconvenient), but I would limit the states to something when the VM is running "normally". if that's a guest service it should be only Up, maybe Migrating too. 
Button(s) should be just grayed out instead of creating/hiding them all the time, ideally.

> I thought briefly about having all the service buttons in a drop down. However, these services will likely be unrelated things (Ex Cockpit, Jupyter Lab, and PhpMyAdmin) and putting them in one drop down may not be the best UX.

it's fine as is. thanks

**Comment by michalskrivanek** [comment]
> it may make sense to introduce a new one or use e.g. canSuspend(yeah, the name is inconvenient), but I would limit the states to something when the VM is running "normally". if that's a guest service it should be only Up, maybe Migrating too.

that would be canRestart which we can use right away

**Comment by rmkraus** [comment]
> > This newest version uses a single custom property called `external_service`. The value of this property is a bar delineated list of NAME|PROTOCOL|PORT. Additional services can be defined by separating them with a comma. So:
> > Service 1|HTTPS|443,Service 2|HTTPS|8080,Service 3|HTTP|80
> 
> thanks, that looks good. I think it would be nicer with "/" (we use that syntax in osinfo) but it's fine as is:)

Changed to be more inline with what is currently done. Having multiple standards doesn't feel good.

> 
> > For every properly formatted service record in the string, a button will be created on the frontend. The button will only be usable if a FQDN is available, the VM canConsole, and it is not a Pool card.
> 
> does it have to be connected to canConsole? it may have a bit too many states...
> export function canConsole (state) {
> return ['up', 'powering_up', 'powering_down', 'paused', 'migrating', 'reboot_in_progress', 'saving_state'].includes(state)
> }
> 
> it may make sense to introduce a new one or use e.g. canSuspend(yeah, the name is inconvenient), but I would limit the states to something when the VM is running "normally". if that's a guest service it should be only Up, maybe Migrating too.
> Button(s) should be just grayed out instead of creating/hiding them all the time, ideally.
> 

Makes sense. Changed to canRestart as requested.

**Comment by sjd78** [comment]
@rmkraus - Also, please squash your commits.  `git rebase -i` and set most to `s`.  This size change really only needs 1 commit.

File: src/components/VmActions/index.js [hunk 5]
```diff
@@ -250,6 +252,30 @@ class VmActions extends React.Component {
...
+    // external_service custom VM param.
+    const fqdn = vm.get('fqdn')
+    const servicesRaw = vm.get('customProperties').find(prop => prop.get('name') === 'external_service') || new Map()
+    if (servicesRaw.get('value')) {
+      // external_service is a bar deliniated list of NAME/PROTOCOL/PORT
+      // multiple services can be defined by chaining them with a comma
+      const services = servicesRaw.get('value').split(',').map(svc => svc.split('/')).filter(svc => svc.length === 3)
+
+      var idx = 0
+      for (const svc of services) {
```
[the remark this answers is not in the document]
Comment (rmkraus) [reply src/components/VmActions/index.js]: 👍 

I'm going to go with the last example. I like the deconstruction, but I also like the filter when parsing the service entries. It prevents an if statement later.

File: src/components/VmActions/index.js [hunk 6]
```diff
@@ -250,6 +252,30 @@ class VmActions extends React.Component {
...
+        actions.push({
+          priority: 0,
+          actionDisabled: isPool || !canExternalService(status, fqdn),
+          shortTitle: svc[0],
+          tooltip: msg.serviceTip(),
```
[the remark this answers is not in the document]
Comment (rmkraus) [reply src/components/VmActions/index.js]: 👍

File: src/intl/messages.js [hunk 7]
```diff
@@ -522,6 +522,7 @@ export const messages: { [messageId: string]: MessageType } = {
   secondsShort: 's',
   sendShortcutKey: 'Send Key',
   sendCtrlAltDel: 'Ctrl+Alt+Del',
+  serviceTip: 'Launch the VM\'s Service',
```
[the remark this answers is not in the document]
Comment (rmkraus) [reply src/intl/messages.js]: 👍

File: src/components/VmActions/index.js [hunk 8]
```diff
@@ -250,6 +252,30 @@ class VmActions extends React.Component {
...
+    // add custom service buttons based on value of the
+    // external_service custom VM param.
+    const fqdn = vm.get('fqdn')
+    const servicesRaw = vm.get('customProperties').find(prop => prop.get('name') === 'external_service') || new Map()
+    if (servicesRaw.get('value')) {
+      // external_service is a bar deliniated list of NAME/PROTOCOL/PORT
+      // multiple services can be defined by chaining them with a comma
+      const services = servicesRaw.get('value').split(',').map(svc => svc.split('/')).filter(svc => svc.length === 3)
+
+      var idx = 0
```
[the remark this answers is not in the document]
Comment (rmkraus) [reply src/components/VmActions/index.js]: 👍

File: src/components/VmActions/index.js [hunk 9]
```diff
@@ -250,6 +252,30 @@ class VmActions extends React.Component {
         items: consoles,
       },
     ]
+
+    // add custom service buttons based on value of the
+    // external_service custom VM param.
+    const fqdn = vm.get('fqdn')
+    const servicesRaw = vm.get('customProperties').find(prop => prop.get('name') === 'external_service') || new Map()
+    if (servicesRaw.get('value')) {
```
[the remark this answers is not in the document]
Comment (rmkraus) [reply src/components/VmActions/index.js]: 👍 

Definitely more readable that way! Thanks.

File: src/components/VmActions/index.js (hunk 4 above)
Comment (rmkraus) [reply src/components/VmActions/index.js]: I'm not sure I know what you mean on this one. Could you provide a bit more detail? 

Right now, MenuItemAction does this for onClick:

```javascript
onClick={() => {                                                         
  onClick && onClick()                                                   
  document.dispatchEvent(new MouseEvent('click'))                        
}
```

**Comment by rmkraus** [comment]
@sjd78 

I implemented all of your suggestions and squashed my commits. 👍 

I'm not sure what other change you wanted for the VM Actions onClick property.

File: src/components/VmActions/index.js (hunk 4 above)
Comment (sjd78) [reply src/components/VmActions/index.js]: Sure.  Here is the action definition for RDP console, which has the `onClick` definition:
https://github.com/oVirt/ovirt-web-ui/blob/09be1f1b36f5972e0efa6c41ca3128053872db58/src/components/VmActions/index.js#L162-L169

The onClick's `e.preventDefault()` will fail since, with the `MenuItemAction` `onClick` implementation you listed, nothing is passed in and e will be `undefined`.  The fix would be the have the `MenuItemAction` `onClick` implementation be:

```jsx
    <MenuItem
      onClick={e => {
        onClick && onClick(e)
        document.dispatchEvent(new MouseEvent('click'))
      }}
      {...rest}
    >
      <span>{shortTitle}</span> {icon}
    </MenuItem>
```

or to use the ... operators to handle all potential function arguments:
```jsx
    <MenuItem
      onClick={(...args) => {
        onClick && onClick(...args)
        document.dispatchEvent(new MouseEvent('click'))
      }}
      {...rest}
    >
      <span>{shortTitle}</span> {icon}
    </MenuItem>
```

Hope that helps.

You can either add that to this PR or spin off a new issue + PR just to handle the "Console RDP button doesn't work".

Comment (rmkraus) [reply src/components/VmActions/index.js]: Thanks so much for taking the time to explain this. I think I got it fixed.

**Comment by rmkraus** [comment]
@sjd78 I put in the fix for the onClick event. Thanks for pointing all that out. I completely missed that! I think this PR should be good with all the requested changes and fixes at this point.

**Comment by sjd78** [comment]
> @sjd78 I put in the fix for the onClick event. Thanks for pointing all that out. I completely missed that! I think this PR should be good with all the requested changes and fixes at this point.

I created #1163 to capture the problem.  Now this PR gets to fix 2 issues.  Thanks!

**Comment by rmkraus** [comment]
👍 

I'm ready to merge when you are.

**Comment by sjd78** [comment]
ci test please
